module.exports = {
    raama: '/raama',
    taotlus_login: '/ou/taotlus_login',
    asutused:'/libs/asutused',
    kontod:'/libs/kontod',
    tunnus:'/libs/tunnus',
    objekt: '/libs/objekt',
    project: '/libs/project',
    isiku_objekt: '/libs/isiku_objekt',
    leping:'/raama/leping',
    isiku_leping:'/raama/isiku_leping',
    nomenclature: '/libs/nomenclature',
    andmed:'/raama/andmed',
    isiku_andmed:'/raama/isiku_andmed',
    arv:'/raama/arv',
    isiku_arv:'/raama/isiku_arv',
    smk:'/raama/smk',
    vmk:'/raama/vmk',
    aa:'/ou/aa',
    kassa:'/ou/kassa',
    sorder:'/raama/sorder',
    vorder:'/raama/vorder',
    userid:'/ou/userid',
    kaive_aruanne:'/raama/kaive_aruanne',
    arved_koodi_jargi:'/raama/arved_koodi_jargi',
    arve_kokkuvote:'/raama/arve_kokkuvote',
    kaibeandmik:'/raama/kaibeandmik',
    kontoandmik:'/raama/kontoandmik',
    rekv: '/ou/rekv',
    pank_vv:'/raama/pank_vv',
    journal:'/raama/journal',
};
